# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='desc',
            field=models.CharField(max_length=120, verbose_name='\u677f\u5757\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u677f\u5757\u540d\u79f0'),
        ),
    ]
