# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20160307_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocks',
            options={'verbose_name': '\u677f\u5757', 'verbose_name_plural': '\u677f\u5757'},
        ),
    ]
