# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AxtivateCode',
            new_name='ActivateCode',
        ),
    ]
